### ISSUE TITLE
Globbing not working for me

### ISSUE THREAD

**Issue by mlunoe** [rlivsey/broccoli-concat#34]
Hi there,

I'm not sure if should post it here, or stackoverflow, but I've tried all that I could think of, and I can't get globbing to work for me. My current file structure is like this:
```
styles/
    application.css
    bootstrap.min.css
```

And I want it to become this after build, with bootstrap.min.css first and then application.css afterwards in main.css:
```
app/css/
    main.css
```

The processing is done like this:
```
// create tree for css
var cssTree = pickFiles("styles", {
  srcDir: "/",
  files: ["**/*.css"],
  destDir: "app/css"
});

cssTree = concatCSS(cssTree, {
  inputFiles: [
    "**/*.css",
    "!app/css/application.css",
    "app/css/application.css"
  ],
  outputFile: "/app/css/main.css",
});
```

If I in stead try globbing like this, it will give me the error `Error: Path or pattern "!styles/application.css" did not match any files`:
```
  inputFiles: [
    "**/*.css",
    "!styles/application.css",
    "styles/application.css"
  ],
```

Is globbing not working as expected, or am I doing it wrong?

**Comment by mlunoe** [comment]
Did you have time to look into this?

**Comment by pierlo-upitup** [comment]
It seems to me that this is because negation patterns are now [disabled by default](https://www.npmjs.com/package/glob#comments-and-negation) in `glob` (which is internally used by the `broccoli-kitchen-sink-helpers`) and are going to be deprecated in v 6. 
While it is possible to override this via a `nonegate: false` option, `broccoli-concat` currently doesn't support [external passing of options to the multiGlob call](https://github.com/rlivsey/broccoli-concat/blob/master/index.js#L71).
